2023-12-11 14:21:29,915 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:20]
2023-12-11 14:22:46,683 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:20]
2023-12-11 17:04:57,153 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:20]
2023-12-11 19:39:26,030 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:20]
2023-12-11 19:39:28,742 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:20]
2023-12-11 21:39:29,468 ERROR: Erro na tarefa combined_task: fetch_and_store_campaign_data() takes 0 positional arguments but 1 was given [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:178]
2023-12-11 21:39:34,309 ERROR: Erro na tarefa combined_task: fetch_and_store_campaign_data() takes 0 positional arguments but 1 was given [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:178]
2023-12-11 23:39:30,885 ERROR: Erro na tarefa combined_task: fetch_and_store_campaign_data() takes 0 positional arguments but 1 was given [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:178]
2023-12-11 23:39:34,524 ERROR: Erro na tarefa combined_task: fetch_and_store_campaign_data() takes 0 positional arguments but 1 was given [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:178]
2023-12-12 01:39:29,625 ERROR: Erro na tarefa combined_task: fetch_and_store_campaign_data() takes 0 positional arguments but 1 was given [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:178]
2023-12-12 01:39:34,434 ERROR: Erro na tarefa combined_task: fetch_and_store_campaign_data() takes 0 positional arguments but 1 was given [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:178]
2023-12-12 03:39:29,865 ERROR: Erro na tarefa combined_task: fetch_and_store_campaign_data() takes 0 positional arguments but 1 was given [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:178]
2023-12-12 03:39:34,349 ERROR: Erro na tarefa combined_task: fetch_and_store_campaign_data() takes 0 positional arguments but 1 was given [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:178]
2023-12-12 05:39:29,453 ERROR: Erro na tarefa combined_task: fetch_and_store_campaign_data() takes 0 positional arguments but 1 was given [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:178]
2023-12-12 05:39:34,382 ERROR: Erro na tarefa combined_task: fetch_and_store_campaign_data() takes 0 positional arguments but 1 was given [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:178]
2023-12-12 07:29:44,619 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:20]
2023-12-12 07:35:05,273 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:20]
2023-12-12 10:05:16,122 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:20]
2023-12-12 10:05:17,216 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:20]
2023-12-12 12:05:28,289 ERROR: Erro na tarefa combined_task: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information. [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:181]
2023-12-12 12:05:28,744 ERROR: Erro na tarefa combined_task: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information. [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:181]
2023-12-12 12:12:18,883 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:20]
2023-12-12 22:05:19,188 ERROR: Erro na tarefa combined_task: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information. [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:181]
2023-12-13 00:05:32,791 ERROR: Erro na tarefa combined_task: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information. [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:181]
2023-12-13 02:05:35,898 ERROR: Erro na tarefa combined_task: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information. [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:181]
2023-12-13 04:05:20,478 ERROR: Erro na tarefa combined_task: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information. [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:181]
2023-12-13 06:05:33,209 ERROR: Erro na tarefa combined_task: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information. [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:181]
2023-12-13 08:05:24,664 ERROR: Erro na tarefa combined_task: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information. [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:181]
2023-12-13 08:33:34,015 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
2023-12-13 09:39:37,277 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
2023-12-13 09:39:38,707 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
2023-12-13 11:37:35,352 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
2023-12-13 11:37:36,698 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
2023-12-13 11:38:03,268 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
2023-12-13 12:45:31,861 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
2023-12-13 12:45:35,285 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
2023-12-13 12:45:46,643 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
2023-12-13 20:22:45,569 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
2023-12-13 21:41:58,520 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
2023-12-13 21:41:59,872 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
2023-12-14 11:36:17,778 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
2023-12-14 11:36:19,176 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
2023-12-18 08:40:00,724 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
2023-12-18 08:40:02,487 INFO: Aplicativo iniciado [in /Users/thiagoa.bento/Library/Mobile Documents/com~apple~CloudDocs/apollo/app.py:18]
